# Generated by staticimports; do not edit by hand.
# ======================================================================
# Imported from pkg:staticimports
# ======================================================================

my_dt_table <-   function(dat,
                          cols_freeze_left = 3,
                          page_length = 10,
                          col_align = 'dt-center', #'dt-right',
                          font_size = '11px',
                          style_input = 'bootstrap',
                          ...){

  dat |>
    DT::datatable(
      ...,
      # style = style_input,
      class = 'cell-border stripe', #'dark' '.table-dark',
      #https://stackoverflow.com/questions/36062493/r-and-dt-show-filter-option-on-specific-columns
      filter = 'top',
      extensions = c("Buttons","FixedColumns", "ColReorder"),
      rownames= FALSE,
      options=list(
        scrollX = TRUE,
        columnDefs = list(list(className = col_align, targets = "_all")), ##just added this
        pageLength = page_length,
        dom = 'lrtipB',
        buttons = c('excel','csv'),
        fixedColumns = list(leftColumns = cols_freeze_left),
        lengthMenu = list(c(5,10,25,50,-1),
                          c(5,10,25,50,"All")),
        colReorder = TRUE,
        #https://stackoverflow.com/questions/44101055/changing-font-size-in-r-datatables-dt
        initComplete = htmlwidgets::JS(glue::glue(
          "function(settings, json) {{ $(this.api().table().container()).css({{'font-size': '{font_size}'}}); }}"
        ))
        #https://github.com/rstudio/DT/issues/1085 - dark theme not working yet
        #   initComplete = JS(
        #     'function() {$("html").attr("data-bs-theme", "dark");}')
      )
    )
  # https://stackoverflow.com/questions/42099418/how-can-i-reduce-row-height-in-dt-datatables - cant get
  # DT::formatStyle(0, target= 'row', lineHeight = row_height_max)
}

#https://stackoverflow.com/questions/49819892/cross-referencing-dtdatatable-in-bookdown
my_tab_caption <- function(
    caption_text = my_caption,
    tip_flag = TRUE,
    tip_text = " <b>NOTE: To view all columns in the table - please click on one of the sort arrows within column headers before scrolling to the right.</b>") {
  # requires results="asis" in chunk header and only works in rmarkdown and not quarto

  cat(
    "<table>",
    paste0(
      "<caption>",
      "(#tab:",
      knitr::opts_current$get()$label,
      ")",
      caption_text,
      if (tip_flag) tip_text,
      "</caption>"
    ),
    "</table>",
    sep = "\n"
  )
}
